- name: Load theme base16.yaml
  ansible.builtin.include_vars:
    file: "{{ role_path }}/files/themes/{{ theme_name }}/base16.yaml"
    name: theme_base16

- name: Read theme polarity
  ansible.builtin.slurp:
    src: "{{ role_path }}/files/themes/{{ theme_name }}/polarity.txt"
  register: theme_polarity_slurp
  changed_when: false

- name: Create theme source directory
  ansible.builtin.file:
    dest: "{{ theme_config_source_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Copy theme wallpaper
  ansible.builtin.copy:
    src: "{{ role_path }}/files/themes/{{ theme_name }}/wp.jpg"
    dest: "{{ theme_config_source_dir }}/wp.jpg"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Copy theme base16
  ansible.builtin.copy:
    src: "{{ role_path }}/files/themes/{{ theme_name }}/base16.yaml"
    dest: "{{ theme_config_source_dir }}/base16.yaml"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Copy theme polarity
  ansible.builtin.copy:
    src: "{{ role_path }}/files/themes/{{ theme_name }}/polarity.txt"
    dest: "{{ theme_config_source_dir }}/polarity"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Set theme polarity fact
  ansible.builtin.set_fact:
    theme_data:
      polarity: "{{ theme_polarity_slurp.content | b64decode | trim }}"
      colors: "{{ theme_base16 }}"
      wallpaper_path: "{{ theme_config_source_dir }}/wp.jpg"
      kb_layout: "{{ theme_kb_layout }}"
      kb_variant: "{{ theme_kb_variant }}"
