- name: Load theme base16.yaml
  ansible.builtin.include_vars:
    file: "{{ role_path }}/files/themes/{{ theme_name }}/base16.yaml"
    name: theme_base16

- name: Read theme polarity
  ansible.builtin.slurp:
    src: "{{ role_path }}/files/themes/{{ theme_name }}/polarity.txt"
  register: theme_polarity_slurp
  changed_when: false

- name: Set theme polarity fact
  ansible.builtin.set_fact:
    theme_data:
      polarity: "{{ theme_polarity_slurp.content | b64decode | trim }}"
      colors: "{{ theme_base16 }}"
      wallpaper_path: "{{ role_path }}/files/themes/{{ theme_name }}/wp.jpg"
