keys:
  - &primary age1nwprvwqfp4lkz2rtjcxhdsxrvlhynlpwcftk7q0ygsvsg4zh2vtqq90css
  - &secondary 616519BF7ABCB7DB2D2FBDBB054FB8F736B2F020
creation_rules:
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *primary
        pgp:
          - *secondary
