user_pw:
    tiwaz: ENC[AES256_GCM,data:9b9yrmbqdP1EOxnmIOY2ZZ22c7rKdaDnmEu+eC5hMUN0hjEGO2meIgOkzsIBGUEgUppgZtCbwkboosaCizfewh75ISSRP2ZuDbG0Ogx/NU1KS2QUs4d9jIeThcm/pZWAFnS/MV2WVFxsUw==,iv:ceryv1KEnsE8wPNuL9YjRY1n6Ryw9lg0uUbS2BluT44=,tag:yNM3vPQDY/Qs7EmQnCaMow==,type:str]
sops:
    age:
        - recipient: age1nwprvwqfp4lkz2rtjcxhdsxrvlhynlpwcftk7q0ygsvsg4zh2vtqq90css
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEthZ1dlNmFuUWpTSVBE
            UWt1TncrV0FkZVJuNnk4VjgyOVJUVzdDVTBzCkhMY1pvbHVaV2hwa0c3K2ZQSlFI
            NTBvbjh1Q1Z1cTVuN2liOVNiTmpVWjQKLS0tIFhRRnkyRms5cStCOC9FQnpzb1dI
            NFBjUVoyMTAxcjNMN1hBbzBqQnBOQ1UK2/ud3JwOHzpmwhpu5w0aTwOMrfqtZe/Y
            SBD9xw5zE1WtsEdiWCi1V9e+3zRUU11DKzqu641mYEo9XOovFAmKVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T16:34:48Z"
    mac: ENC[AES256_GCM,data:mMHipT+ZYnKsefieYZ45OTK6muAir8O/aGRTRuNAhTPJTiTlMzLLewKCaRpt8PgmDoHj4GuoxAJcf04t2tQP6dsMqeKkHupZ3vyye2J+DFWLnKOICDzIA6ONBkyRxAzOeFZekccUomiFyuplJe9k467lhCKJaEJib4J+EmP9eJk=,iv:Is4UE3g55rlaLYQtF9OEo064HDO+0J4Y1dtmqh4koe0=,tag:VWSO8Eb0Lc7pdWwimSeoDg==,type:str]
    pgp:
        - created_at: "2026-01-16T16:19:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DXKw2WNkTzdESAQdAld89EZtgmQ0/MCggjLR2fE0yzDRUzELZBfKdDKOz2mgw
            63K5F1Ml6b4bWDWCYMq/7hRGoeAhLF5XNF2mzwVsMujWH25e7ZQ8pHGM4AFRKOJz
            0l4Bga0Ol/n0+qEMgEDImbOqmQcBrUh0retXgMOPi9g9UE9eCh+CenZrgOSY/a9G
            HCcTOASeSNXWBLpl+XFeKxECetYzFl3EJ/TvLk3OgOC/YFVGRhT5mzPc8j8/he52
            =lsf0
            -----END PGP MESSAGE-----
          fp: 616519BF7ABCB7DB2D2FBDBB054FB8F736B2F020
    unencrypted_suffix: _unencrypted
    version: 3.11.0
