user_pw:
    tiwaz: ENC[AES256_GCM,data:5Nf7vk3g0nCBEAUa5r7y4zsGWtKNfRmPIKM4HTAy+NeMPPALdvRcckBK4C2cdncQezgFHe6pPXYnE7RN,iv:AgI6H/3054SZvlACZytZ1fEvoqvgLRRU4IzoaERmtqM=,tag:1ffkz+5HTt8vBsyx1Rposw==,type:str]
sops:
    age:
        - recipient: age1nwprvwqfp4lkz2rtjcxhdsxrvlhynlpwcftk7q0ygsvsg4zh2vtqq90css
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEthZ1dlNmFuUWpTSVBE
            UWt1TncrV0FkZVJuNnk4VjgyOVJUVzdDVTBzCkhMY1pvbHVaV2hwa0c3K2ZQSlFI
            NTBvbjh1Q1Z1cTVuN2liOVNiTmpVWjQKLS0tIFhRRnkyRms5cStCOC9FQnpzb1dI
            NFBjUVoyMTAxcjNMN1hBbzBqQnBOQ1UK2/ud3JwOHzpmwhpu5w0aTwOMrfqtZe/Y
            SBD9xw5zE1WtsEdiWCi1V9e+3zRUU11DKzqu641mYEo9XOovFAmKVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T19:18:09Z"
    mac: ENC[AES256_GCM,data:8watT10JA0EJGDGOnZHW/oa9ZbusZ4F00kNVVrOkWmHtVIas4v2efL+MlrH6SA+JmnEvHkuzyt2fL7I5rGnRYwp3ROm/pXp88JTcOfGKP4nKc1cNf2jtirL+S8id2FxQHuePoC2AFHv6DfNDPNn/yYiyb3uOmOiXoiy4gwmZRqs=,iv:Z6oX3AjnmQSd+cggfZNUJpNadbHl90ROkFpybzdS92E=,tag:vl5T1klygXSNsAWg3N5tww==,type:str]
    pgp:
        - created_at: "2026-01-16T16:19:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DXKw2WNkTzdESAQdAld89EZtgmQ0/MCggjLR2fE0yzDRUzELZBfKdDKOz2mgw
            63K5F1Ml6b4bWDWCYMq/7hRGoeAhLF5XNF2mzwVsMujWH25e7ZQ8pHGM4AFRKOJz
            0l4Bga0Ol/n0+qEMgEDImbOqmQcBrUh0retXgMOPi9g9UE9eCh+CenZrgOSY/a9G
            HCcTOASeSNXWBLpl+XFeKxECetYzFl3EJ/TvLk3OgOC/YFVGRhT5mzPc8j8/he52
            =lsf0
            -----END PGP MESSAGE-----
          fp: 616519BF7ABCB7DB2D2FBDBB054FB8F736B2F020
    unencrypted_suffix: _unencrypted
    version: 3.11.0
