user_pw:
    tiwaz: ENC[AES256_GCM,data:5Nf7vk3g0nCBEAUa5r7y4zsGWtKNfRmPIKM4HTAy+NeMPPALdvRcckBK4C2cdncQezgFHe6pPXYnE7RN,iv:AgI6H/3054SZvlACZytZ1fEvoqvgLRRU4IzoaERmtqM=,tag:1ffkz+5HTt8vBsyx1Rposw==,type:str]
primary_key: ENC[AES256_GCM,data:Cg/DarGY2bzpTlcFRW49ux2Guaho4PbJU1UCcEC+7FCxGLBxfop0Bfh664EizmrLhfAIPVJeXVzjwqeWZcG4GpqxrgNaq+SzPi20JUCTN21NfO/UzDLO1LONaYllYetv6HsVmsj1M/c4pvXRwHqQl1XkxvqXZqjQLhzFZi4mWtyFjQUbvcikaRDNHTcBji+QirDI/wQZ3Fs=,iv:s3A9qsPiGUjPzQp4re3AyqedSd7Q8YUKiMsvwJmxONw=,tag:U4o9QuEgNfknoK6EuKKY3A==,type:str]
sops:
    age:
        - recipient: age1nwprvwqfp4lkz2rtjcxhdsxrvlhynlpwcftk7q0ygsvsg4zh2vtqq90css
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEthZ1dlNmFuUWpTSVBE
            UWt1TncrV0FkZVJuNnk4VjgyOVJUVzdDVTBzCkhMY1pvbHVaV2hwa0c3K2ZQSlFI
            NTBvbjh1Q1Z1cTVuN2liOVNiTmpVWjQKLS0tIFhRRnkyRms5cStCOC9FQnpzb1dI
            NFBjUVoyMTAxcjNMN1hBbzBqQnBOQ1UK2/ud3JwOHzpmwhpu5w0aTwOMrfqtZe/Y
            SBD9xw5zE1WtsEdiWCi1V9e+3zRUU11DKzqu641mYEo9XOovFAmKVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T10:39:20Z"
    mac: ENC[AES256_GCM,data:GlcPaJ5reP/8PJxijwuqMcCXr1UUIlgZHGshAXCH8z6LyCsc0GcFbh26qp4FiAVIjccJQ68slk9158P5ogDvCkQb0ypHwEtsg9Ni3OW7H45byATiGLabqCgLPWmsQ39SY27oGtp995Q5GEFt3g/V8oQ36dxXNfOvmViDca9a3A8=,iv:CLwTQv0l4Z4d/xr+yD5UvzMESNyVEozwSEps6sTloPk=,tag:+CN+98771LyTVoIOXXANYA==,type:str]
    pgp:
        - created_at: "2026-01-16T16:19:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DXKw2WNkTzdESAQdAld89EZtgmQ0/MCggjLR2fE0yzDRUzELZBfKdDKOz2mgw
            63K5F1Ml6b4bWDWCYMq/7hRGoeAhLF5XNF2mzwVsMujWH25e7ZQ8pHGM4AFRKOJz
            0l4Bga0Ol/n0+qEMgEDImbOqmQcBrUh0retXgMOPi9g9UE9eCh+CenZrgOSY/a9G
            HCcTOASeSNXWBLpl+XFeKxECetYzFl3EJ/TvLk3OgOC/YFVGRhT5mzPc8j8/he52
            =lsf0
            -----END PGP MESSAGE-----
          fp: 616519BF7ABCB7DB2D2FBDBB054FB8F736B2F020
    unencrypted_suffix: _unencrypted
    version: 3.12.1
