atlas:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:UWhrexBh7eunnYs0M51nhqAZxyZYSLjK8RQ2RelOtrszaDQT/MMP5z4ZFeWaCidPrterqV+nGo59zDRZbJ+vL6e726XFuIxs6azz+HpnIqnb9XXfX6bih0mVMtpzpjB0OH45l/TklXjDQ8oAQMgGNjgTHVquI6wX3VoKpqPMXofi8pMyv+vL+p9BKMfzQDZCBCpILCGiGo/duxO8mFjslJ4wOLriUNRBJ9WNlX3OHpBtpbUam6RT0KdGlX2XrM7Y1TZ+wDVEaoJUZ3GmvylbLHIF1J43NE6lHPqUXuzh4NtpNPKuDFJkNYo398FCZDy73IuVjkO7CmE0hCak95JDIDv0CPfmyVB/mm+BbZHzWiJZEPAZ4wpN7I8DKGUcsVR7MTEo/9GdVrnFLBOGVldrpnJBDOsVRYpimWvLAz/Ovd9LsZTCm0YBHXwVmH5CKzd0HYVwKtn6a8ihBpRAIGKItGoovSvK8AQSu5khIymrVpEtgnfdVXOogjnZpG12QpzQ2mYrzfPP7zWVf4xgeq03joEoAE+as6P7gShp,iv:VB2Q9mOs1l/GG2NFSU3vMkgzvW6efL5Ejo/i89/fyMs=,tag:DRL5pP7CViz3I3mAdDZsDA==,type:str]
sops:
    age:
        - recipient: age1nwprvwqfp4lkz2rtjcxhdsxrvlhynlpwcftk7q0ygsvsg4zh2vtqq90css
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcWpSNWtESVdTcFNGWHhw
            OTBURFlWbWE4SjI5MUR1dFN4a0tmTEZocFRVCjVxcVl1b2pPTTdXMzZUMGZPQVhD
            bGw2Skw4dDM2eFJXNllHZkx5YlRRRE0KLS0tIHBhNEpMNGc0OGJwUXZaM2J0WE5m
            ajJXVXBqaWRKb3k3eGxXRjQyRUwxZkEK9BfDFZXOXBizNlkqknQ/mMcRul2bTs+j
            t3LytRSw68dJ4UN4w4PIHS1knGYBcHo6pe4/WlIveRSs/WiQzJiqTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T16:36:02Z"
    mac: ENC[AES256_GCM,data:cP/7hPw1u0xMX/tLZBogjwYjdV9SKtBkWKx+2KwVghaGEl3R9f/Fc1BIQycZXo9MLbTpgb16mqKHsruVx5xyNueoEscbLgWDkJ0/KXNGHGkqTrxGdc4QOAWJF2OI35hU94Jk1jAv3R+YqnemV6XIbovlDDG9p3fJpyPPsCqhDNE=,iv:pLQliwyEZGyc5m2VMNU6JwPCTvJl2R7DexS7fdsr8K8=,tag:7nNwQt2vTjdOnl9ZoEUD0Q==,type:str]
    pgp:
        - created_at: "2026-01-16T16:03:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DXKw2WNkTzdESAQdAD9tVsu4txMgWtQZxZIOWukoeP2/a7Jvr/JjUe8vynUgw
            jmyG+qLopJ/tWq6tGmIeoIyYEtZs3V+hEB/m+mh8jrg170d4CZIgh5pPAg65reV2
            0l4BjQ2VoLe+fE+307DcSemG03eNq59QMjMp46ZXdYmxxzsVzosGo5OHWwDPT5TH
            g4Ri+7BxIU7PiWmHTDUxUkmCOvl/MBp5eFH5htAVxpne6mWnn8+s5SNUgwECc5Up
            =XL48
            -----END PGP MESSAGE-----
          fp: 616519BF7ABCB7DB2D2FBDBB054FB8F736B2F020
    unencrypted_suffix: _unencrypted
    version: 3.11.0
