- name: Install Hyprland desktop suite
  community.general.pacman:
    name:
      - hyprland
      - hyprlock
      - hypridle
      - kitty
      - yazi
      - rofi
      - waybar
      - dunst
      - uwsm
    state: present
  become: true
  tags: [desktop_hyprland, packages]

- name: Install Hyprland must haves
  community.general.pacman:
    name:
      - xdg-desktop-portal-hyprland
      - hyprpolkitagent
      - qt5-wayland
      - qt6-wayland
    state: present
  become: true
  tags: [desktop_hyprland, packages]

- name: Install Hyprland utils
  community.general.pacman:
    name:
      - hyprcursor
      - hyprpwcenter
      - wl-clipboard
      - brightnessctl
      - playerctl
    state: present
  become: true
  tags: [desktop_hyprland, packages]

- name: Install wallpaper utilities
  community.general.pacman:
    name:
      - hyprpaper
      - wlr-randr
      - jq
    state: present
  become: true
  tags: [desktop_hyprland, packages]

- name: Install Greetd login manager
  community.general.pacman:
    name:
      - greetd
      - greetd-tuigreet
    state: present
  become: true
  tags: [desktop_hyprland, packages, greetd]

- name: Install optional yazi file manager dependencies
  community.general.pacman:
    name:
      - ffmpeg
      - p7zip
      - jq
      - poppler
      - fd
      - ripgrep
      - fzf
      - zoxide
      - imagemagick
    state: present
  become: true
  tags: [desktop_hyprland, packages]

- name: Create config folder
  ansible.builtin.file:
    dest: "{{ hyprland_source_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  tags: [desktop_hyprland, config]

- name: Copy greetd configuration
  ansible.builtin.copy:
    src: greetd-config.toml
    dest: "{{ hyprland_source_dir }}/greetd-config.toml"
    owner: root
    group: root
    mode: "0644"
  become: true
  tags: [desktop_hyprland, config, greetd]

- name: Generate tmpfiles.d configuration for greetd symlink
  ansible.builtin.template:
    src: tmpfiles-greetd-symlinks.conf.j2
    dest: /usr/lib/tmpfiles.d/bootc-greetd-symlinks.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  tags: [desktop_hyprland, tmpfiles, symlinks, greetd]

- name: Enable Greetd
  ansible.builtin.systemd_service:
    name: greetd.service
    enabled: true
  become: true
  tags: [desktop_hyprland, systemd]
