- name: Install base utils
  community.general.pacman:
    name:
      - git
      - git-lfs
      - nvim
      - lazygit
      - eza
      - jq
      - yq
      - zoxide
      - fzf
      - imagemagick
  become: true
  tags: [tools, packages]

- name: Install monitoring utils
  community.general.pacman:
    name:
      - fastfetch
      - btop
      - nvtop
  become: true
  tags: [tools, packages]
