secrets_sops_config: "{{ playbook_dir }}/secrets/.sops.yaml"
secrets_host: "{{ playbook_dir }}/secrets/host_secrets.yaml"
secrets_global: "{{ playbook_dir }}/secrets/global_secrets.yaml"

secrets_source_dir: "/usr/local/share/config/secrets"
secrets_script_path: "/usr/local/bin/decrypt-secrets"

secrets_age_key_path: "/var/lib/sops/age/key.txt"
secrets_runtime_dir: "/run/secrets"

secrets_packages:
  - sops
  - yq

secrets_paths:
  global: {}
