- name: Install software
  community.general.pacman:
    name:
      - hyprland # base desktop suite
      - hyprlock
      - hypridle
      - kitty
      - yazi
      - rofi
      - waybar
      - dunst
      - uwsm
      - xdg-desktop-portal-hyprland # must have's
      - hyprpolkitagent
      - qt5-wayland
      - qt6-wayland
      - swww # for wallpaper
      - wlr-randr
      - greetd # Login screen
      - greetd-tuigreet
      - ffmpeg # yazi optional dependencies
      - p7zip
      - jq
      - poppler
      - fd
      - ripgrep
      - fzf
      - zoxide
      - imagemagick
    state: present
  become: true
  tags: [desktop_hyprland, packages]

- name: Create config folder
  ansible.builtin.file:
    dest: "{{ desktop_hypr_source_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  tags: [desktop_hyprland, config]

- name: Copy file configurations
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ desktop_hypr_source_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - greetd-config.toml
    - waybar-modules-custom.jsonc
    - waybar-modules-groups.jsonc
    - waybar-modules.jsonc
    - waybar-modules-workspaces.jsonc
  become: true
  tags: [desktop_hyprland, config]

- name: Render template configurations
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ desktop_hypr_source_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - dunstrc
    - hypridle.conf
    - hyprland.conf
    - hyprlock.conf
    - rofi-config.rasi
    - waybar-config
    - waybar-style.css
    - yazi-syntect.tmTheme
    - yazi-theme.toml
    - yazi.toml
  become: true
  tags: [desktop_hyprland, config]

- name: Generate tmpfiles.d configuration for user symlinks
  ansible.builtin.template:
    src: tmpfiles-hypr-symlinks.conf.j2
    dest: /usr/lib/tmpfiles.d/bootc-hypr-symlinks.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  tags: [desktop_hyprland, tmpfiles, symlinks]

- name: Create greetd config directory
  ansible.builtin.file:
    dest: /etc/greetd
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  tags: [desktop_hyprland, config, greetd]

- name: Generate tmpfiles.d configuration for greetd symlink
  ansible.builtin.template:
    src: tmpfiles-greetd-symlinks.conf.j2
    dest: /usr/lib/tmpfiles.d/bootc-greetd-symlinks.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  tags: [desktop_hyprland, tmpfiles, symlinks, greetd]

- name: Enable Greetd
  ansible.builtin.systemd_service:
    name: greetd.service
    enabled: true
  become: true
  tags: [desktop_hyprland, systemd]
