- name: Validate symlink keys for host {{ validate_hostname }}
  ansible.builtin.assert:
    that:
      - secrets_host_keys[validate_hostname] is defined
      - secrets_host_keys[validate_hostname] | json_query(secret_query) is not none
    fail_msg: "Secret '{{ validate_hostname }}.{{ item.key }}' referenced in paths does not exist in {{ secrets_host }}"
    success_msg: "Secret '{{ item.key }}' exists for host {{ validate_hostname }}"
  vars:
    secret_query: "{{ item.key }}"
  loop: "{{ secrets_paths[validate_hostname] | dict2items }}"
  tags: [secrets, validate]
