- name: Install audio software
  community.general.pacman:
    name:
      - pipewire
      - pipewire-jack
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
  become: true
  tags: [desktop_hardware, packages]

- name: Install bluetooth software
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
      - blueman
  become: true
  tags: [desktop_hardware, packages]

- name: Enable bluetooth service
  ansible.builtin.systemd_service:
    name: bluetooth.service
    enabled: true
  become: true
  tags: [desktop_hardware, bluetooth]

- name: Install drive software
  community.general.pacman:
    name:
      - udisks2
  become: true
  tags: [desktop_hardware, packages]
