- name: Configure system
  hosts: localhost
  connection: local
  roles:
    - base_config
    - greetd
    - hardware
    - hyprland
    - network
    - secrets
    - ssh
    - tools
    - user_creation
    - virt
    - xdg
