- name: Configure system
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Set container_hostname fact from /etc/hostname
      ansible.builtin.set_fact:
        container_hostname: "{{ lookup('ansible.builtin.file', '/etc/hostname') }}"
      tags: [always]

  roles:
    - secrets
    - theme
